// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/agent-chat/AgentChat.tsx": () => import("../components/mockups/agent-chat/AgentChat.tsx")
};
